// This file is auto-generated by scripts/compile.ts. Do not edit this file directly.

export type Author = {
  name: string;
  title: string;
  url: string;
  image_url: string;
};

export type Blog = {
  title: string;
  tags?: string[];
  authors: Author[];
  path: string;
  date: string;
  thumbnail: string;
};

export type Release = {
  title: string;
  authors: Author[];
  path: string;
  date: string;
  version: string;
};

// Sort by date descending
export const latestBlogs: Blog[] = [
  {
    title: "2023 Year in Review",
    path: "/blog/mlflow-year-in-review",
    tags: ["MLflow", "2023", "Linux Foundation"],
    authors: [
      {
        name: "Carly Akerly",
        title: "OSS Marketing Consultant at The Linux Foundation",
        url: "https://www.linkedin.com/in/carlyakerly/",
        image_url:
          "https://media.licdn.com/dms/image/D4E03AQGccXoDMQGe8w/profile-displayphoto-shrink_400_400/0/1707268516995?e=1713398400&v=beta&t=AMO6IRfMLpVEiZ-RDBK8t68H1cPpBGpoQA9CBj8FwUQ",
      },
    ],
    date: "2024-01-26",
    thumbnail: "img/blog/2023-year-in-review.png",
  },
  {
    title: "Streamline your MLflow Projects with Free Hosted MLflow",
    path: "/blog/databricks-ce",
    tags: ["managed mlflow", "getting started"],
    authors: [
      {
        name: "Abe Omorogbe",
        title: "Product Manager, ML at Databricks",
        url: "https://www.linkedin.com/in/abeomor/",
        image_url:
          "https://media.licdn.com/dms/image/D4E03AQG-dAkLO2hx_Q/profile-displayphoto-shrink_400_400/0/1693252025753?e=1711584000&v=beta&t=02Bl1a73vp7Zpt8ZXSK_BRDF6DIZWAx1l8oSgkWNa5g",
      },
    ],
    date: "2024-01-25",
    thumbnail: "img/blog/databricks-ce.png",
  },
  {
    title: "Custom MLflow Models with mlflow.pyfunc",
    path: "/blog/custom-pyfunc",
    tags: ["pyfunc", "models"],
    authors: [
      {
        name: "Daniel Liden",
        title: "Developer Advocate at Databricks",
        url: "https://www.linkedin.com/in/danielliden",
        image_url: "https://github.com/djliden.png",
      },
    ],
    date: "2024-01-23",
    thumbnail: "img/blog/custom-pyfunc.png",
  },
];

// Sort by date descending
export const latestReleases: Release[] = [
  {
    title: "MLflow 2.10.2",
    path: "/releases/2.10.2",
    authors: [
      {
        name: "MLflow maintainers",
        title: "MLflow maintainers",
        url: "https://github.com/mlflow/mlflow.git",
        image_url: "https://github.com/mlflow-automation.png",
      },
    ],
    date: "2024-02-09",
    version: "2.10.2",
  },
  {
    title: "MLflow 2.10.1",
    path: "/releases/2.10.1",
    authors: [
      {
        name: "MLflow maintainers",
        title: "MLflow maintainers",
        url: "https://github.com/mlflow/mlflow.git",
        image_url: "https://github.com/mlflow-automation.png",
      },
    ],
    date: "2024-02-06",
    version: "2.10.1",
  },
  {
    title: "MLflow 2.10.0",
    path: "/releases/2.10.0",
    authors: [
      {
        name: "MLflow maintainers",
        title: "MLflow maintainers",
        url: "https://github.com/mlflow/mlflow.git",
        image_url: "https://github.com/mlflow-automation.png",
      },
    ],
    date: "2024-01-26",
    version: "2.10.0",
  },
];
