// This file is auto-generated by scripts/compile.ts. Do not edit this file directly.

export type Author = {
  name: string;
  title: string;
  url: string;
  image_url: string;
};

export type Blog = {
  title: string;
  tags?: string[];
  authors: Author[];
  path: string;
  date: string;
  thumbnail?: string;
};

export type Release = Blog & { version: string };

// Sort by date descending
export const latestBlogs: Blog[] = [
  {
    title: "MLflow AI Gateway renamed to MLflow Deployments for LLMs",
    path: "blog/2023/12/01/ai-gateway-rename",
    tags: ["ai"],
    authors: [
      {
        name: "MLflow maintainers",
        title: "MLflow maintainers",
        url: "https://github.com/mlflow/mlflow.git",
        image_url: "https://github.com/mlflow-automation.png",
      },
    ],
    date: "2023-12-01",
    thumbnail: "img/blog/ai-gateway.png",
  },
  {
    title:
      "Automatic Metric, Parameter, and Artifact Logging with mlflow.autolog",
    path: "blog/2023/11/30/mlflow-autolog",
    tags: ["autolog"],
    authors: [
      {
        name: "Daniel Liden",
        title: "Developer Advocate at Databricks",
        url: "https://www.linkedin.com/in/danielliden",
        image_url: "https://github.com/djliden.png",
      },
    ],
    date: "2023-11-30",
    thumbnail: "img/blog/mlflow-autolog.png",
  },
  {
    title: "MLflow Docs Overhaul",
    path: "blog/2023/10/31/mlflow-docs-overhaul",
    tags: ["docs"],
    authors: [
      {
        name: "MLflow maintainers",
        title: "MLflow maintainers",
        url: "https://github.com/mlflow/mlflow.git",
        image_url: "https://github.com/mlflow-automation.png",
      },
    ],
    date: "2023-10-31",
    thumbnail: "img/blog/docs-overhaul.png",
  },
];

// Sort by date descending
export const latestReleases: Release[] = [
  {
    title: "MLflow 2.9.2",
    path: "releases/2023/12/14/2.9.2-release",
    authors: [
      {
        name: "MLflow maintainers",
        title: "MLflow maintainers",
        url: "https://github.com/mlflow/mlflow.git",
        image_url: "https://github.com/mlflow-automation.png",
      },
    ],
    date: "2023-12-14",
    version: "2.9.2",
  },
  {
    title: "MLflow 2.9.1",
    path: "releases/2023/12/07/2.9.1-release",
    authors: [
      {
        name: "MLflow maintainers",
        title: "MLflow maintainers",
        url: "https://github.com/mlflow/mlflow.git",
        image_url: "https://github.com/mlflow-automation.png",
      },
    ],
    date: "2023-12-07",
    version: "2.9.1",
  },
  {
    title: "MLflow 2.9.0",
    path: "releases/2023/12/06/2.9.0-release",
    authors: [
      {
        name: "MLflow maintainers",
        title: "MLflow maintainers",
        url: "https://github.com/mlflow/mlflow.git",
        image_url: "https://github.com/mlflow-automation.png",
      },
    ],
    date: "2023-12-06",
    version: "2.9.0",
  },
];
