name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "website/**"
      - ".github/**"
  push:
    branches:
      - main
    paths:
      - "website/**"
      - ".github/**"

permissions:
  contents: read

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: website
        run: npm ci

      - name: Build website
        working-directory: website
        env:
          GTM_ID: ${{ secrets.GTM_ID }}
        run: npm run build

      - name: Set artifact name
        id: artifact
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "name=website-build-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "name=website-build-main" >> $GITHUB_OUTPUT
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: website/build
          retention-days: 1
