name: E2E

on:
  pull_request:
  schedule:
    # Run this job daily to detect dead slack invite links
    - cron: "0 0 * * *"

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 20
      - working-directory: website
        run: npm ci
      - working-directory: website
        run: npm run e2e-setup
      - working-directory: website
        run: npm run build
      - working-directory: website
        run: npm run e2e-test
