name: E2E

on:
  pull_request:
  schedule:
    # Run this job daily to detect dead slack invite links
    - cron: "0 0 * * *"

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20
      - working-directory: website
        run: npm ci
      - working-directory: website
        run: npm run e2e-setup
      - working-directory: website
        run: npm run build
      - working-directory: website
        run: npm run e2e-test
