name: External Link Checker

on:
  schedule:
    # Runs at 13:00 UTC every day
    - cron: "0 13 * * *"
  workflow_dispatch: # Allow manual runs
  pull_request:
    paths:
      - ".github/workflows/link-checker.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: website

jobs:
  check-external-links:
    # Only run on the main repository
    if: github.repository == 'mlflow/mlflow-website'
    permissions:
      contents: read
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run external links checker
        env:
          CHECK_EXTERNAL_LINKS: "true"
        run: npm run check-links
