name: Link Checker

on:
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: website

jobs:
  check-links:
    if: github.repository == 'mlflow/mlflow-website'
    permissions:
      contents: read
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Check links
        run: npm run check-links
