name: Deploy PR Preview to Netlify

on:
  workflow_run:
    workflows: ["PR Build"]
    types:
      - completed

permissions:
  actions: write
  contents: read
  pull-requests: write

jobs:
  deploy-preview:
    name: Deploy Preview to Netlify
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download PR number artifact
        uses: actions/github-script@v7
        env:
          ARTIFACT_NAME: pr-number
        with:
          script: |
            const { downloadArtifact } = require('./.github/scripts/artifact-utils.js');
            await downloadArtifact({ github, context });

      - name: Read PR number
        id: get-pr
        run: |
          PR_NUMBER=$(cat pr-number.txt)
          echo "result=$PR_NUMBER" >> $GITHUB_OUTPUT
          rm pr-number.txt

      - name: Download build artifacts
        uses: actions/github-script@v7
        env:
          ARTIFACT_NAME: website-build-${{ steps.get-pr.outputs.result }}
          EXTRACT_PATH: website/build
        with:
          script: |
            const { downloadArtifact } = require('./.github/scripts/artifact-utils.js');
            await downloadArtifact({ github, context });

      - name: Clean up GitHub artifacts
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.get-pr.outputs.result }}
        with:
          script: |
            // Remove artifacts immediately after download to save storage space
            // and keep the repository clean. Artifacts are no longer needed
            // once they've been extracted for deployment.
            const { deleteArtifacts } = require('./.github/scripts/artifact-utils.js');
            await deleteArtifacts({ github, context });

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        working-directory: website
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          PR_NUMBER: ${{ steps.get-pr.outputs.result }}
          ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          netlify deploy \
            --dir=build \
            --no-build \
            --message="PR Preview #${PR_NUMBER} - GitHub Action: ${ACTION_URL}" \
            --alias="pr-${PR_NUMBER}"

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.get-pr.outputs.result }}
          NETLIFY_DOMAIN: ${{ secrets.NETLIFY_SITE_NAME }}
          DEPLOY_ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          BUILD_ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
        with:
          script: |
            const script = require('./.github/scripts/preview-comment.js');
            await script({ github, context });
